[2025-03-14T14:59:40.049+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-14T14:59:40.061+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mtrix_vendas_edi.process_txt_to_postgres manual__2025-03-14T14:59:38.498735+00:00 [queued]>
[2025-03-14T14:59:40.065+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mtrix_vendas_edi.process_txt_to_postgres manual__2025-03-14T14:59:38.498735+00:00 [queued]>
[2025-03-14T14:59:40.066+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-14T14:59:40.073+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): process_txt_to_postgres> on 2025-03-14 14:59:38.498735+00:00
[2025-03-14T14:59:40.079+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=70) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-14T14:59:40.080+0000] {standard_task_runner.py:72} INFO - Started process 72 to run task
[2025-03-14T14:59:40.081+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'mtrix_vendas_edi', 'process_txt_to_postgres', 'manual__2025-03-14T14:59:38.498735+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/mtrix_vendas_edi.py', '--cfg-path', '/tmp/tmpzjew3xaj']
[2025-03-14T14:59:40.082+0000] {standard_task_runner.py:105} INFO - Job 51: Subtask process_txt_to_postgres
[2025-03-14T14:59:40.119+0000] {task_command.py:467} INFO - Running <TaskInstance: mtrix_vendas_edi.process_txt_to_postgres manual__2025-03-14T14:59:38.498735+00:00 [running]> on host 266a86bf832d
[2025-03-14T14:59:40.177+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='user' AIRFLOW_CTX_DAG_ID='mtrix_vendas_edi' AIRFLOW_CTX_TASK_ID='process_txt_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-03-14T14:59:38.498735+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-14T14:59:38.498735+00:00'
[2025-03-14T14:59:40.177+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-14T14:59:40.194+0000] {logging_mixin.py:190} INFO - Processando arquivo: /opt/***/data/arquivos_mtrix/VENDASUN12032025140133.txt
[2025-03-14T14:59:40.284+0000] {logging_mixin.py:190} INFO - âœ… Inseridos 363 registros de VENDASUN12032025140133.txt!
[2025-03-14T14:59:40.284+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-14T14:59:40.292+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-14T14:59:40.293+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=mtrix_vendas_edi, task_id=process_txt_to_postgres, run_id=manual__2025-03-14T14:59:38.498735+00:00, execution_date=20250314T145938, start_date=20250314T145940, end_date=20250314T145940
[2025-03-14T14:59:40.334+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-14T14:59:40.346+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-14T14:59:40.348+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
