[2025-03-14T13:29:55.313+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-14T13:29:55.324+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mtrix_clientes_edi.ingest_clientes_mtrix manual__2025-03-14T13:29:54.087999+00:00 [queued]>
[2025-03-14T13:29:55.329+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mtrix_clientes_edi.ingest_clientes_mtrix manual__2025-03-14T13:29:54.087999+00:00 [queued]>
[2025-03-14T13:29:55.330+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-14T13:29:55.337+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): ingest_clientes_mtrix> on 2025-03-14 13:29:54.087999+00:00
[2025-03-14T13:29:55.343+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=76) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-14T13:29:55.344+0000] {standard_task_runner.py:72} INFO - Started process 78 to run task
[2025-03-14T13:29:55.345+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'mtrix_clientes_edi', 'ingest_clientes_mtrix', 'manual__2025-03-14T13:29:54.087999+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/mtrix_clientes_edi.py', '--cfg-path', '/tmp/tmp7779zu49']
[2025-03-14T13:29:55.347+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask ingest_clientes_mtrix
[2025-03-14T13:29:55.382+0000] {task_command.py:467} INFO - Running <TaskInstance: mtrix_clientes_edi.ingest_clientes_mtrix manual__2025-03-14T13:29:54.087999+00:00 [running]> on host e1b30e32018f
[2025-03-14T13:29:55.447+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mtrix_clientes_edi' AIRFLOW_CTX_TASK_ID='ingest_clientes_mtrix' AIRFLOW_CTX_EXECUTION_DATE='2025-03-14T13:29:54.087999+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-14T13:29:54.087999+00:00'
[2025-03-14T13:29:55.448+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-14T13:29:55.462+0000] {logging_mixin.py:190} INFO - Arquivo 'CLIENTESUN12032025140133.txt' j√° foi processado. Pulando.
[2025-03-14T13:29:55.462+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-14T13:29:55.470+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-14T13:29:55.471+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=mtrix_clientes_edi, task_id=ingest_clientes_mtrix, run_id=manual__2025-03-14T13:29:54.087999+00:00, execution_date=20250314T132954, start_date=20250314T132955, end_date=20250314T132955
[2025-03-14T13:29:55.518+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-14T13:29:55.528+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-14T13:29:55.529+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
